### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by darrinholst** [jbuedel/AgentRalphPlugin#3]
Sorry for the n00b question, but I'm new to VS and ReSharper. How do you install this?

**Comment by jbuedel** [comment]
In Visual Studio, Go to ReSharper->Extension Manager->Online. Then search for "AgentRalph".

The bad news is that AgentRalph is not updated for the latest version of ReSharper. It's one version behind I believe. If you are on the latest version, it won't install for you. I hope to update this soon.

**Comment by darrinholst** [comment]
Ah, that must be why it didn't show up in the search. Thanks.

**Comment by jbuedel** [comment]
@darrinholst I've updated the plugin for R# 8.2.  Thanks for trying out AgentRalph.

**Comment by darrinholst** [comment]
Got it installed. Thanks

**Comment by cyberfish-dev** [comment]
@jbuedel , can you make update for the latest resharper pleeease? I searched all net and did not find any plugin that works well, currently installed CodeRush, but uninstalled right away because it is a laggy nightmare.. I just need warn-highlighting of code clones and VS 2015 does not have that, they even did not have grouping by projects, so I cannot find out if my currently written file has clones or not.. please help :)

**Comment by caverna** [comment]
Thumbs up!
